"""first migration

Revision ID: cb5414bd2ba6
Revises: 
Create Date: 2020-12-13 02:33:19.777222

"""
from alembic import op, context
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb5414bd2ba6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('pswd', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('auctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), server_default='now()', nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auctions_created'), 'auctions', ['created'], unique=False)
    op.create_index(op.f('ix_auctions_end'), 'auctions', ['end'], unique=False)
    op.create_index(op.f('ix_auctions_is_active'), 'auctions', ['is_active'], unique=False)
    op.create_index(op.f('ix_auctions_name'), 'auctions', ['name'], unique=False)
    op.create_index(op.f('ix_auctions_owner'), 'auctions', ['owner'], unique=False)
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auction', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['auction'], ['auctions.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bets_auction'), 'bets', ['auction'], unique=False)
    op.create_index(op.f('ix_bets_created'), 'bets', ['created'], unique=False)
    op.create_index(op.f('ix_bets_price'), 'bets', ['price'], unique=False)
    op.create_index(op.f('ix_bets_user'), 'bets', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bets_user'), table_name='bets')
    op.drop_index(op.f('ix_bets_price'), table_name='bets')
    op.drop_index(op.f('ix_bets_created'), table_name='bets')
    op.drop_index(op.f('ix_bets_auction'), table_name='bets')
    op.drop_table('bets')
    op.drop_index(op.f('ix_auctions_owner'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_name'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_is_active'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_end'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_created'), table_name='auctions')
    op.drop_table('auctions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass
